# Generated by Django 3.0.5 on 2020-04-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('popular_name', models.CharField(max_length=30, verbose_name='Nome popular')),
                ('slug', models.SlugField(verbose_name='nome')),
                ('birth', models.DateField(blank=True, verbose_name='Nascimento')),
                ('death', models.DateField(blank=True, verbose_name='Falecimento')),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='author/images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pt', models.CharField(max_length=50, verbose_name='Título PT')),
                ('title_original', models.CharField(max_length=50, verbose_name='Título original')),
                ('slug', models.CharField(max_length=50, verbose_name='titulo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('pages', models.IntegerField(verbose_name='Páginas')),
                ('isbn10', models.CharField(blank=True, max_length=10, verbose_name='ISBN 10')),
                ('isbn13', models.CharField(blank=True, max_length=13, verbose_name='ISBN 13')),
                ('cdd', models.CharField(blank=True, max_length=10, verbose_name='CDD')),
                ('cdu', models.CharField(blank=True, max_length=10, verbose_name='CDU')),
                ('summary', models.TextField()),
                ('cover', models.ImageField(upload_to='cover/images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.Author')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='País')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Sigla')),
                ('slug', models.SlugField(unique=True, verbose_name='pais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Gênero')),
                ('slug', models.SlugField(verbose_name='genero')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Editora')),
                ('slug', models.SlugField(verbose_name='editora')),
                ('page', models.CharField(max_length=20, verbose_name='Site')),
                ('logo', models.ImageField(upload_to='publisher/images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='BookRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.Book')),
            ],
            options={
                'verbose_name_plural': 'Books Rate',
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.Book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.Genre')),
            ],
            options={
                'verbose_name_plural': 'Books Genre',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.Country'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.Publisher'),
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='siteapp.Country'),
        ),
    ]
